# Generated by Django 2.2.10 on 2023-12-30 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_kart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='item_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sale',
            name='temp_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='temp_value',
            field=models.IntegerField(),
        ),
    ]
